### ISSUE TITLE
Design changes to developer advocate pages

### ISSUE THREAD

**Issue by anita-trimbur** [pulumi/pulumi-hugo#1306]
### High Priority

- [x] Reposition “See all developer advocates” link to match specs and reintroduce the dropdown navigation in the upper right.
- [x] Speaking subsection is missing tabs to separate “Upcoming” from “Past” engagements. This would allow a fourth column to appear in “Past” to contain the “Slides” links. 
- [x] Links to slides should make it clear what will happen on-click. If it will download a PDF, the link should say “Download” with the associated icon. If it takes the user to an external link, it should say “External Link” with the associated icon. 
- [x] Add secondary “View Profile” buttons on the dev advocate landing page. Unclear now that the profiles are clickable.

### Medium Priority

- [x] The added subheading for the role title should be stylized more prominently. Size relation to the body text feels off. Would recommend Gilroy Bold, #4A5568, 20px.
- [x] Body text for the profile intros should be resized from 18px to 16px. The text should also wrap underneath the profile image
- [x] Reintroduce the giveaway card. If there are constraints from the DA team, we can also amend the existing design for any type of giveaway, not just Pulumi swag.
- [x] Increase cell padding in the Speaking table on small screen widths.
- [x] Pulumipus takes up too much space without adding value; I would recommend removing.

### Low Priority

- [x] Social icons should be displayed with the text user handles.
- [x] Secondary headings (Speaking, Recent Blog Posts, Get in Touch) should have the hex code #4A5568
- [x] Text in the Speaking table should have the hex code #4A5568. Table headers should have the hex code #2E3032.
- [x] Standardize max-height for all blog images in the Recent Blog Posts subsection.
- [x] Reduce space between “Recent Blog Posts” and “Get in Touch” subsections
- [x] Colored dots should be included next to the contact form.
- [x] See new stylization of contact form once submitted. This will allow the form container to stay the same height so the colored dots won’t have to reposition after form submission.
- [ ] Form field should read “How can I help you?” instead of “How can we help you?”
- [x] Softer drop shadow on the contact form matches other instances of these cards. Y = 6, Blur = 36. 1px stroke should be removed.
